add_subdirectory(visualizations)
add_subdirectory(physics_engines)
add_subdirectory(media)
add_subdirectory(entities)
add_subdirectory(external_estimator)
if(FILAMENT_FOUND)
  add_subdirectory(photorealism)
  find_package(ARGoSSDL2)
  if(ARGOS_SDL2_FOUND)
    add_subdirectory(visualizations/filament)
  else()
    message(STATUS "SDL2 not found; skipping the Filament visualization")
  endif()
endif(FILAMENT_FOUND)
