# Generated inclines are always available; external SubT assets and the
# downstream SwarmDeck step helper are opt-in, never fetched by these tests.
function(add_spot_terrain_test name)
  add_test(NAME jolt_mesh_spot_${name}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    COMMAND ${CMAKE_BINARY_DIR}/core/argos3 -zc ${name}.argos)
  set_tests_properties(jolt_mesh_spot_${name} PROPERTIES
    ENVIRONMENT "ARGOS_PLUGIN_PATH=${ARGOS_PLUGIN_PATH}")
endfunction()
foreach(ANGLE 16 18)
  set(TERRAIN_CASE ramp${ANGLE})
  # Release horizontally 20 cm above the ramp centerline, then drive uphill.
  if(ANGLE EQUAL 16)
    set(TERRAIN_POSITION "1,0,0.486745")
  else()
    set(TERRAIN_POSITION "1,0,0.524920")
  endif()
  set(TERRAIN_CHECKS "maximum_tilt=\"25\"")
  configure_file(terrain.argos.in ${TERRAIN_CASE}.argos)
  add_spot_terrain_test(${TERRAIN_CASE})
endforeach()

set(ARGOS_JOLT_SUBT_MESH "" CACHE FILEPATH "Optional SubT finals collision GLB for Spot replay")
if(ARGOS_JOLT_SUBT_MESH)
  foreach(POSE flat approach entry pinned)
    set(SUBT_YAW 176)
    set(SUBT_POSITION "15.6175,-20.3375,0.001")
    if(POSE STREQUAL "approach")
      set(SUBT_YAW 177.6)
      set(SUBT_POSITION "13.6213,-20.1694,0.012")
    elseif(POSE STREQUAL "entry")
      set(SUBT_YAW -179.6)
      set(SUBT_POSITION "12.4591,-20.1238,0.030")
    elseif(POSE STREQUAL "pinned")
      set(SUBT_YAW -151)
      set(SUBT_POSITION "11.6,-20,0.04")
    endif()
    set(SUBT_LEFT 30)
    set(SUBT_RIGHT 30)
    set(SUBT_TRAVEL 2.5)
    configure_file(subt.argos.in subt_${POSE}.argos)
    add_spot_terrain_test(subt_${POSE})
  endforeach()
  foreach(YAW_TENTHS 4 8 12)
    math(EXPR SUBT_LEFT "30 - ${YAW_TENTHS} * 25 / 10")
    math(EXPR SUBT_RIGHT "30 + ${YAW_TENTHS} * 25 / 10")
    set(SUBT_TRAVEL 0)
    configure_file(subt.argos.in subt_replay_${YAW_TENTHS}.argos)
    add_spot_terrain_test(subt_replay_${YAW_TENTHS})
  endforeach()
endif()

option(ARGOS_JOLT_STEP_TESTS "Test externally applied SwarmDeck step helper" OFF)
if(ARGOS_JOLT_STEP_TESTS)
  foreach(HEIGHT 10 20 30)
    set(TERRAIN_CASE step${HEIGHT})
    set(TERRAIN_POSITION "0,0,0")
    set(TERRAIN_CHECKS "maximum_tilt=\"15\" expect_z=\"0.${HEIGHT}\" position_tolerance=\"0.02\"")
    configure_file(terrain.argos.in ${TERRAIN_CASE}.argos)
    add_spot_terrain_test(${TERRAIN_CASE})
  endforeach()
endif()
