# Generated inclines, steps and obstructions are always available. External
# SubT assets are opt-in and never fetched by these tests.
function(add_spot_terrain_test name)
  add_test(NAME jolt_mesh_spot_${name}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    COMMAND ${CMAKE_BINARY_DIR}/core/argos3 -zc ${name}.argos)
  set_tests_properties(jolt_mesh_spot_${name} PROPERTIES
    ENVIRONMENT "ARGOS_PLUGIN_PATH=${ARGOS_PLUGIN_PATH}")
endfunction()
set(TERRAIN_MIN_TRAVEL 2.5)
set(TERRAIN_SPEED 30)
set(TERRAIN_OBSTACLES "")
set(TERRAIN_COMMANDS "")
set(TERRAIN_COMMAND_SEQUENCE "")
set(TERRAIN_LENGTH 10)
foreach(ANGLE 16 18)
  set(TERRAIN_CASE ramp${ANGLE})
  # Start parallel to the surface, 2 mm above it: measure driven traversal,
  # not the impact velocity of the former horizontal settling drop.
  set(TERRAIN_ORIENTATION "0,-${ANGLE},0")
  if(ANGLE EQUAL 16)
    set(TERRAIN_POSITION "1,0,0.288745")
  else()
    set(TERRAIN_POSITION "1,0,0.326920")
  endif()
  # A 3 m commanded path projects to about 2.85 m uphill along X.
  # Bound final X as well as path length: downhill travel must not qualify.
  set(TERRAIN_CHECKS "maximum_tilt=\"25\" expect_x=\"3.85\" position_tolerance=\"0.25\"")
  configure_file(terrain.argos.in ${TERRAIN_CASE}.argos)
  add_spot_terrain_test(${TERRAIN_CASE})
endforeach()

# Cone/contact opposition: stand on a 35-degree slope at the 30-degree cone.
# Initial height clears the leading corner by 2 mm; default friction is 1.0.
set(TERRAIN_CASE ramp35)
set(TERRAIN_POSITION "1,0,0.760726172")
set(TERRAIN_ORIENTATION "0,-30,0")
set(TERRAIN_MIN_TRAVEL 0)
set(TERRAIN_SPEED 0)
set(TERRAIN_CHECKS "maximum_tilt=\"30.1\" cone_contact_check=\"true\"")
configure_file(terrain.argos.in cone_slope35.argos)
add_spot_terrain_test(cone_slope35)
set(TERRAIN_MIN_TRAVEL 2.5)
set(TERRAIN_SPEED 30)

foreach(HEIGHT 10 20 30 35)
  set(TERRAIN_CASE step${HEIGHT})
  set(TERRAIN_POSITION "0,0,0")
  set(TERRAIN_ORIENTATION "0,0,0")
  set(TERRAIN_CHECKS "step_check=\"true\" maximum_up_speed=\"0.5001\" maximum_tilt=\"30.1\" expect_z=\"0.${HEIGHT}\" position_tolerance=\"0.02\"")
  configure_file(terrain.argos.in ${TERRAIN_CASE}.argos)
  add_spot_terrain_test(${TERRAIN_CASE})
endforeach()

set(TERRAIN_CASE step35)
set(TERRAIN_CHECKS "step_check=\"true\" maximum_up_speed=\"0.5001\" maximum_tilt=\"30.1\" expect_z=\"0.35\" position_tolerance=\"0.02\" reset_tick=\"20\" reset_ground_check=\"true\"")
configure_file(terrain.argos.in step_reset.argos)
add_spot_terrain_test(step_reset)
string(REPLACE "reset_tick" "move_tick" TERRAIN_CHECKS "${TERRAIN_CHECKS}")
configure_file(terrain.argos.in step_move_to.argos)
add_spot_terrain_test(step_move_to)

set(TERRAIN_MIN_TRAVEL 2.0)
foreach(INTERRUPT stop turn lift tiny_reverse)
  set(INTERRUPT_TICK 45)
  if(INTERRUPT STREQUAL "lift" OR INTERRUPT STREQUAL "tiny_reverse")
    set(INTERRUPT_TICK 20)
  endif()
  set(TERRAIN_COMMANDS "interrupt_tick=\"${INTERRUPT_TICK}\" interrupt_ticks=\"20\"")
  set(HOLD_YAW 0)
  set(TERRAIN_COMMAND_SEQUENCE "")
  if(INTERRUPT STREQUAL "turn")
    # Turn out and back within the same two-second hold before resuming.
    string(APPEND TERRAIN_COMMANDS " interrupt_left=\"-10\" interrupt_right=\"10\"")
    set(TERRAIN_COMMAND_SEQUENCE "<command tick=\"55\" left=\"10\" right=\"-10\" /><command tick=\"65\" left=\"30\" right=\"30\" />")
    set(HOLD_YAW 0.3)
  endif()
  if(INTERRUPT STREQUAL "tiny_reverse")
    string(APPEND TERRAIN_COMMANDS " interrupt_left=\"-0.01\" interrupt_right=\"-0.01\"")
  endif()
  set(TERRAIN_CHECKS "step_check=\"true\" maximum_tilt=\"30.1\" expect_z=\"0.35\" position_tolerance=\"0.02\" interrupt_tick=\"${INTERRUPT_TICK}\" interrupt_ticks=\"20\" minimum_hold_yaw=\"${HOLD_YAW}\"")
  configure_file(terrain.argos.in step_interrupt_${INTERRUPT}.argos)
  add_spot_terrain_test(step_interrupt_${INTERRUPT})
endforeach()
foreach(PAUSE_CASE turn_advance turn_lift long timeout)
  set(TERRAIN_COMMANDS "")
  set(TERRAIN_COMMAND_SEQUENCE "")
  set(TERRAIN_LENGTH 20)
  set(TERRAIN_MIN_TRAVEL 2.0)
  set(PAUSE_START 45)
  if(PAUSE_CASE STREQUAL "turn_lift" OR PAUSE_CASE STREQUAL "timeout")
    set(PAUSE_START 20)
  endif()
  if(PAUSE_CASE MATCHES "^turn_")
    foreach(OFFSET 20 30 40 50 60)
      math(EXPR TICK_${OFFSET} "${PAUSE_START} + ${OFFSET}")
    endforeach()
    # Turn 1.6 rad; try forward above 90 deg and again at 0.8 rad; realign.
    set(TERRAIN_COMMAND_SEQUENCE "
      <command tick=\"${PAUSE_START}\" left=\"-20\" right=\"20\" />
      <command tick=\"${TICK_20}\" left=\"30\" right=\"30\" />
      <command tick=\"${TICK_30}\" left=\"20\" right=\"-20\" />
      <command tick=\"${TICK_40}\" left=\"30\" right=\"30\" />
      <command tick=\"${TICK_50}\" left=\"20\" right=\"-20\" />
      <command tick=\"${TICK_60}\" left=\"30\" right=\"30\" />")
    set(TERRAIN_CHECKS "step_check=\"true\" step_deadline=\"13\" maximum_tilt=\"30.1\" expect_z=\"0.35\" position_tolerance=\"0.02\" interrupt_tick=\"${PAUSE_START}\" interrupt_ticks=\"60\" minimum_hold_yaw=\"1.5999\"")
  elseif(PAUSE_CASE STREQUAL "long")
    set(TERRAIN_COMMANDS "interrupt_tick=\"45\" interrupt_ticks=\"100\"")
    set(TERRAIN_CHECKS "step_check=\"true\" step_deadline=\"17\" maximum_tilt=\"30.1\" expect_z=\"0.35\" position_tolerance=\"0.02\" interrupt_tick=\"45\" interrupt_ticks=\"100\"")
  else()
    # Expire above unobstructed lower ground during lift; then remain stopped.
    set(TERRAIN_LENGTH 36)
    set(TERRAIN_MIN_TRAVEL 0)
    set(TERRAIN_COMMANDS "interrupt_tick=\"20\" interrupt_ticks=\"10000\"")
    set(TERRAIN_CHECKS "maximum_tilt=\"30.1\" expect_z=\"0\" position_tolerance=\"0.02\" interrupt_tick=\"20\" interrupt_ticks=\"300\" drop_check=\"true\" drop_start_tick=\"320\"")
  endif()
  configure_file(terrain.argos.in step_pause_${PAUSE_CASE}.argos)
  add_spot_terrain_test(step_pause_${PAUSE_CASE})
endforeach()
set(TERRAIN_LENGTH 10)
set(TERRAIN_COMMANDS "")
set(TERRAIN_COMMAND_SEQUENCE "")
set(TERRAIN_MIN_TRAVEL 0)
set(TERRAIN_CHECKS "maximum_rise=\"0.03\" maximum_tilt=\"30.1\" expect_x=\"0.45\" expect_z=\"0\" position_tolerance=\"0.03\"")
set(TERRAIN_CASE step40)
configure_file(terrain.argos.in step_too_high.argos)
add_spot_terrain_test(step_too_high)
set(TERRAIN_CASE step10)
set(TERRAIN_OBSTACLES "<box id=\"ceiling\" size=\"5,5,0.1\" movable=\"false\"><body position=\"2,0,0.75\" orientation=\"0,0,0\" /></box>")
configure_file(terrain.argos.in step_ceiling.argos)
add_spot_terrain_test(step_ceiling)

set(ARGOS_JOLT_SUBT_MESH "" CACHE FILEPATH "Optional SubT finals collision GLB for Spot replay")
if(ARGOS_JOLT_SUBT_MESH)
  foreach(POSE flat approach entry pinned)
    set(SUBT_YAW 176)
    set(SUBT_POSITION "15.6175,-20.3375,0.001")
    if(POSE STREQUAL "approach")
      set(SUBT_YAW 177.6)
      set(SUBT_POSITION "13.6213,-20.1694,0.012")
    elseif(POSE STREQUAL "entry")
      set(SUBT_YAW -179.6)
      set(SUBT_POSITION "12.4591,-20.1238,0.030")
    elseif(POSE STREQUAL "pinned")
      set(SUBT_YAW -151)
      set(SUBT_POSITION "11.6,-20,0.04")
    endif()
    set(SUBT_LEFT 30)
    set(SUBT_RIGHT 30)
    # Retain the measured route progress, with about 2 cm numerical margin.
    set(SUBT_TRAVEL 2.94)
    if(POSE STREQUAL "flat")
      set(SUBT_TRAVEL 2.95)
    elseif(POSE STREQUAL "pinned")
      set(SUBT_TRAVEL 2.86)
    endif()
    configure_file(subt.argos.in subt_${POSE}.argos)
    add_spot_terrain_test(subt_${POSE})
  endforeach()
  foreach(YAW_TENTHS 4 8 12)
    math(EXPR SUBT_LEFT "30 - ${YAW_TENTHS} * 25 / 10")
    math(EXPR SUBT_RIGHT "30 + ${YAW_TENTHS} * 25 / 10")
    set(SUBT_TRAVEL 0)
    configure_file(subt.argos.in subt_replay_${YAW_TENTHS}.argos)
    add_spot_terrain_test(subt_replay_${YAW_TENTHS})
  endforeach()
endif()
